config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do

    root    'pages#home'
    
    get     'pages/home'

    get     'sessions/new'

    get     'sessions/create'

    get     'users/new'

    get     '/signup'   => 'users#new' 
    post    '/signup'   => 'users#create'

    get     '/login'    => 'sessions#new'
    post    '/login'    => 'sessions#create'
    delete  '/logout'   => 'sessions#destroy'

    resources :users

    resources "contacts", only: [:new, :create]

  end

      

      

end

app/models/contact.rb
class Contact < MailForm::Base
  
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "My Contact Form",
      :to => "your_email@example.org",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/user.rb
class User < ActiveRecord::Base

	before_save { self.email = email.downcase }
	validates :username,  presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

	validates :admin, inclusion: { in: [true, false] }
	validates :admin, exclusion: { in: [nil] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  before_filter :set_locale

  def set_locale
    # if cookies[:educator_locale] && I18n.available_locales.include?(cookies[:educator_locale].to_sym)
    #   l = cookies[:educator_locale].to_sym
    # else
    #   l = I18n.default_locale
    #   cookies.permanent[:educator_locale] = l
    # end
    #   I18n.locale = l
    I18n.locale = params[:locale] if params[:locale].present?
  end

  def default_url_options(options = {})
    {locale: I18n.locale}
  end
  # helper_method :current_user, :logged_in?

  # private

    # helper_method :current_user, :logged_in?

  # def current_user
  	# @current_user ||= User.find(session[:user_id]) if session[:user_id]
    # User.where(id: session[:user_id]).first
  ############
      # return unless session[:user_id]
      # @current_user ||= User.find(session[:user_id])
  # end

  # def logged_in?
      # current_user.nil?
  # end

  # def require_user
  # 	redirect_to '#' unless current_user
  	
  # end


end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

	def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
      flash.now[:notice] = 'Thank you for your message!'
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@title = "FramWork1"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
  	@user = User.find_by_email(params[:session][:email])
  	if @user && @user.authenticate(params[:session][:password])
  		# session[:user_id] = @user_id
      log_in @user
      flash[:success] = "Successfully logged in"
  		redirect_back_or @user
  	else
  	# 	redirect_to '/login'
      flash.now[:danger] = 'Invalid email/password combination' # Not quite right!
      render 'new'
    end  
  end

  def destroy
    session[:user_id] = nil 
    flash[:success] = "Successfully logged out"
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: [:destroy, :index]

  def index
    @users = User.paginate(page: params[:page])   
  end

  def show
    @user = User.find(params[:id])
    @name = @user.username
  end

  def new
  	@user = User.new
  	@title = "Sign up"
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  	# 	session[:user_id] = @user.id
  	# 	redirect '/'
  	# else
  	# 	redirect '/signup'
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
  	end
  end

  def edit
    @user = User.find(params[:id])    
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  private

  def user_params
  	params.require(:user).permit(:username, :email, :password, :password_confirmation, :admin)	
  end

  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end

  # Confirms the correct user.
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user) || current_user.admin?
  end

  # Confirms an admin user.
  def admin_user
    #redirect_to(root_url) unless current_user.admin?
    unless users_admin?
      flash[:danger] = "You have to be admin... :-p"
      redirect_to(root_url)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	# Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end
  
	# Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
    # @current_user ||= User.find(session[:user_id]) if session[:user_id] 
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

  def users_admin?
    current_user.admin?
  end

  # Redirects to stored location (or to the default).
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  # Stores the URL trying to be accessed.
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/create.html.erb
<div class="container">
  <h1> Thank you for your message.</h1>
  <p> We'll get back to you soon.</p>
</div>

app/views/contacts/new.html.erb
<!-- <div class="container">
  <h1> Contact </h1>
  <%= simple_form_for @contact, :html => {:class => 'form-horizontal' } do |f| %>
  	<%= render 'shared/error_messages_contacts', object: @contact %>
    <%= f.input :name, :required => true %>
    <%= f.input :email, :required => true %>
    <%= f.input :message, :as => :text, :required => false, :input_html => {:rows => 10} %>
    <div class="hidden">
      <%= f.input :nickname, :hint => 'Leave this field blank!' %>
    </div>
    <div class="form-actions">
      <%= f.button :submit, 'Send message', class: "btn btn-primary" %>
    </div>
    <% end %>
</div> -->

<h1> Contact </h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@contact) do |f| %>
	    	<%= render 'shared/error_messages_contacts', object: @contact %>

			<%= f.label t('forms.name'), :required => true %>
			<p><%= f.text_field :name , class: 'form-control' %></p>

			<%= f.label :email %>
			<p><%= f.email_field :email, class: 'form-control'  %> </p>

			<%= f.label :message %>
			<p><%= f.text_area( :message, rows: 10) %> </p>

			<p><%= f.submit t('forms.send_m'), class: "btn btn-primary" %></p>
			<% end %>

	</div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    FrameWork1 by lpavius</a>
  </small>
  <nav>
    <ul>
      <!-- <li><%= link_to "About",   '#' %></li> -->
      <li><%= link_to "Contact", new_contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "framework app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t('header.home'), root_path %></li>
          <% if logged_in? %>
            <% if users_admin? %>
                <li><%= link_to t('header.users'), users_path %></li>
            <% end %>    
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= t('header.account') %><b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to t('header.profile'), current_user %></li>
                <li><%= link_to t('header.setting'), edit_user_path(current_user) %></li>
                <li><%= link_to "Forum", '#' %></li>
                <li class="divider"></li>
                <li><%= link_to t('header.logout'), logout_path, method: "delete" %></li> 
              </ul>
            </li>
          <% else %>
            <li><%= link_to t('header.login'), login_path %></li>
          <% end %>
          <% if I18n.locale == :en %>
            <li><%= link_to flag_icon(:fr) , locale: :fr %></li>
          <% else %>
            <li><%= link_to flag_icon(:gb), locale: :en %></li>
          <% end %>        
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>
	<!-- <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "sample app", '#', id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Home",   '#' %></li> -->
            <!-- <li><%= link_to "Help",   '#' %></li> -->
            <!-- <li><%= link_to "Log in", '#' %></li>
          </ul>
        </nav>
      </div>
    </header> -->
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
		<%= yield %>
		<%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
	</div>
</body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @title %></title>
  </head>
  <body>
	<div class="center jumbotron">
		<h1><%= t('welcome.title') %>Framework App</h1>
		<% if !logged_in? %>
			<%= link_to t('welcome.signup'), signup_path, class: "btn btn-lg btn-primary" %>
		<% end %>
	</div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messages_contacts.html.erb
<% if @contact.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@contact.errors.count, "error") %>.
    </div>
    <ul>
    <% @contact.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
	<%= render 'shared/error_messages', object: @user %>

	<%= f.label t('forms.username') %>
	<p><%= f.text_field :username , class: 'form-control' %></p>

	<%= f.label :email %>
	<p><%= f.email_field :email, class: 'form-control'  %> </p>

	<%= f.label t('forms.password') %>
	<p><%= f.password_field :password, class: 'form-control' %> </p>

	<%= f.label :password_confirmation, "Confirmation" %>
	<p><%= f.password_field :password_confirmation, class: 'form-control' %> </p>

	<p><%= f.submit yield(:button_text), class: "btn btn-primary" %></p>
<% end %>

app/views/users/_user.html.erb
	

	<tr >
		<td style="padding-right: 100px"><%= link_to user.username, user_path(user) %></td>
	<!-- <% if current_user.admin? && !current_user?(user) %> -->
		<td style="padding-right: 20px"><%= link_to "Edit", edit_user_path(user), class: "btn btn-info" %></td>
		<!-- <input type="checkbox"> Check me out -->
		<td><%= link_to "Delete", user, method: :delete, data: { confirm: "You sure?" }, class: "btn btn-danger" %></td>
	<!-- <% end %> -->
		<!-- <td><%= form_for(user) do |f| %>admin
			<%= f.check_box :admin, {:readonly => true}, true, false %>
			<p><%= f.submit "Ok", class: "btn btn-primary" %></p> -->
		<% end %></td>
</tr>

app/views/users/edit.html.erb
<% provide(:title, t('titles.edit')) %>
<% provide(:button_text, t('forms.save')) %>
<h1><%= t('titles.update') %></h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">

		<%= render 'form' %>

	</div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1><%= t('titles.all') %></h1>

<%= will_paginate %>

<table >
	<%= render @users %>
</table>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, t('forms.sign')) %>
<% provide(:button_text, t('forms.create')) %>
<h1><%= t('titles.sign') %></h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">

    	<%= render 'form' %>

	</div>
</div>

app/views/users/show.html.erb
<div class="row">
	<aside class="col-md-4">
		<section class="user_info">

			<% if @user.admin? %>
				<p>(admin)</p>
			<% end %>
			<h1><%= @name %></h1>

			
		</section>
	</aside>
</div>